"""Explainer folders: one per explained subject, ``docs/explain/<NNNN>-<slug>/``.

Each subject (a feature, branch, project or part) gets a unique, never reused ID and a
name. Its folder holds the explainer (``README.md``) and its pictures (``img/``);
``docs/explain/README.md`` lists them all. Explaining the same subject again reuses its
folder, so the ID and links stay stable.
"""

from __future__ import annotations

import re
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

from kingmadoc.exceptions import ExplainError
from kingmadoc.naming import slugify

EXPLAIN_DIR = Path("docs/explain")
EXPLAINER_FILE = "README.md"
ID_WIDTH = 4
_FOLDER = re.compile(r"(\d{4,})-(.+)")
_TITLE = re.compile(r"^#\s+(.+?)(?::\s.*)?$", re.M)
_SCOPE = re.compile(r"^\|\s*\*\*Scope\*\*\s*\|\s*(.*?)\s*\|", re.M)
_BASED_ON = re.compile(r"^\|\s*\*\*Based on\*\*\s*\|.*?(\d{4}-\d{2}-\d{2})", re.M)


@dataclass(frozen=True)
class Entry:
    """One explainer folder, as listed in the index."""

    id: str
    folder: str
    name: str
    scope: str
    date: str
    has_explainer: bool


def explainer_folder(root: Path, name: str) -> tuple[Path, bool]:
    """Return the folder for a subject, creating it with a new ID when it is new.

    Args:
        root: Project root.
        name: Subject name ("Contact form", "branch feature-x") or an existing ID ("3").

    Returns:
        ``(folder, created)``.

    Raises:
        ExplainError: If the name is blank or the folder cannot be created.
    """
    slug = slugify(name) if name.strip() else ""
    if not slug:
        raise ExplainError("The subject needs a name, e.g. kingmadoc explain new \"Contact form\"")
    directory = root / EXPLAIN_DIR
    folders = _folders(directory)
    wanted_id = int(name) if name.strip().isdigit() else None
    for number, folder in folders:
        if folder.name.partition("-")[2] == slug or number == wanted_id:
            return folder, False
    number = max((n for n, _ in folders), default=0) + 1
    folder = directory / f"{number:0{ID_WIDTH}d}-{slug}"
    try:
        folder.mkdir(parents=True)
    except OSError as exc:
        raise ExplainError(f"Cannot create {folder}: {exc}") from exc
    return folder, True


def read_entries(directory: Path) -> list[Entry]:
    """Read the name, scope and date of every explainer folder in ``directory``.

    Args:
        directory: The ``docs/explain`` directory.

    Returns:
        The entries in ID order; the folder's slug stands in for a missing explainer.
    """
    entries = []
    for _, folder in _folders(directory):
        number, _, slug = folder.name.partition("-")
        doc = folder / EXPLAINER_FILE
        text = doc.read_text(encoding="utf-8", errors="replace") if doc.is_file() else ""
        title, scope, date = _TITLE.search(text), _SCOPE.search(text), _BASED_ON.search(text)
        entries.append(Entry(
            id=number,
            folder=folder.name,
            name=title.group(1).strip() if title else slug,
            scope=scope.group(1).replace("|", "/") if scope else "",
            date=date.group(1) if date else "",
            has_explainer=doc.is_file(),
        ))
    return entries


def index_markdown(entries: Sequence[Entry]) -> str:
    """Render ``docs/explain/README.md``: one row per explainer.

    Args:
        entries: From :func:`read_entries`.

    Returns:
        The Markdown index.
    """
    lines = [
        "# Explained code",
        "",
        "One folder per explained subject (`<ID>-<name>/`), written by the KingmaDoc",
        "`explaining-code` skill. IDs are never reused. Regenerated by `kingmadoc explain`",
        "and `kingmadoc render`; do not edit by hand.",
        "",
        "| ID | Subject | Scope | Date |",
        "| --- | --- | --- | --- |",
    ]
    for e in entries:
        target = f"{e.folder}/{EXPLAINER_FILE}" if e.has_explainer else f"{e.folder}/"
        lines.append(f"| {e.id} | [{e.name}]({target}) | {e.scope} | {e.date} |")
    if not entries:
        lines.append("| | _No explainers yet._ | | |")
    return "\n".join(lines) + "\n"


def index_path(document: Path) -> Path | None:
    """Return the index a rendered document belongs to, or None outside explainer folders.

    Args:
        document: A document passed to ``kingmadoc render``.

    Returns:
        ``docs/explain/README.md`` when ``document`` is ``docs/explain/<NNNN>-<slug>/…``.
    """
    folder = document.resolve().parent
    parts = EXPLAIN_DIR.parts
    if _FOLDER.fullmatch(folder.name) and folder.parent.parts[-len(parts):] == parts:
        return folder.parent / EXPLAINER_FILE
    return None


def _folders(directory: Path) -> list[tuple[int, Path]]:
    if not directory.is_dir():
        return []
    found = [(int(m.group(1)), p) for p in directory.iterdir()
             if p.is_dir() and (m := _FOLDER.fullmatch(p.name))]
    return sorted(found)
