"""Explainer folders: one per explained subject, ``docs/explain/<NNNN>-<slug>/``.

Each subject (a feature, branch, project or part) gets a unique, never reused ID and a
name. Its folder holds the explainer (``README.md``) and its pictures (``img/``);
``docs/explain/README.md`` lists them all. Explaining the same subject again reuses its
folder, so the ID and links stay stable.
"""

from __future__ import annotations

import re
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

from kingmadoc.exceptions import ExplainError
from kingmadoc.git import run_git
from kingmadoc.naming import slugify

EXPLAIN_DIR = Path("docs/explain")
EXPLAINER_FILE = "README.md"
ID_WIDTH = 4
_FOLDER = re.compile(r"(\d{4,})-(.+)")
_TITLE = re.compile(r"^#\s+(.+?)(?::\s.*)?$", re.M)
_SCOPE = re.compile(r"^\|\s*\*\*Scope\*\*\s*\|\s*(.*?)\s*\|", re.M)
_BASED_ON = re.compile(r"^\|\s*\*\*Based on\*\*\s*\|.*?(\d{4}-\d{2}-\d{2})", re.M)
_FENCE = re.compile(r"^(```|~~~).*?^\1[ \t]*$", re.S | re.M)
INDEX_TITLE = "# Explained code"
_BASED_ON_ROW = re.compile(r"^\|\s*\*\*Based on\*\*\s*\|(.*)$", re.M)
_COMMIT = re.compile(r"\b[0-9a-f]{7,40}\b")
_CODE_SPAN = re.compile(r"`([^`\n]+)`")
INDEX_MARKER = "<!-- kingmadoc:explain-index -->"


@dataclass(frozen=True)
class Entry:
    """One explainer folder, as listed in the index."""

    id: str
    link: str
    name: str
    scope: str
    date: str


def explainer_folder(root: Path, name: str) -> tuple[Path, bool]:
    """Return the folder for a subject, creating it with a new ID when it is new.

    Args:
        root: Project root.
        name: Subject name ("Contact form", "branch feature-x") or an existing ID ("3").

    Returns:
        ``(folder, created)``.

    Raises:
        ExplainError: If the name is blank or the folder cannot be created.
    """
    slug = slugify(name) if name.strip() else ""
    if not slug:
        raise ExplainError("The subject needs a name, e.g. kingmadoc explain new \"Contact form\"")
    directory = root / EXPLAIN_DIR
    folders = _folders(directory)
    wanted_id = int(name) if name.strip().isdigit() else None
    for number, folder in folders:
        if folder.name.partition("-")[2] == slug or number == wanted_id:
            return folder, False
    number = max((n for n, _ in folders), default=0) + 1
    folder = directory / f"{number:0{ID_WIDTH}d}-{slug}"
    try:
        folder.mkdir(parents=True)
    except OSError as exc:
        raise ExplainError(f"Cannot create {folder}: {exc}") from exc
    return folder, True


def read_entries(directory: Path) -> list[Entry]:
    """Read the name, scope and date of every explainer folder in ``directory``.

    Args:
        directory: The ``docs/explain`` directory.

    Returns:
        The entries in ID order; the folder's slug stands in for a missing explainer.
        Explainers from before the folders (``docs/explain/<slug>.md``) follow, without ID.
    """
    entries = []
    for _, folder in _folders(directory):
        number, _, slug = folder.name.partition("-")
        doc = folder / EXPLAINER_FILE
        link = f"{folder.name}/{EXPLAINER_FILE}" if doc.is_file() else f"{folder.name}/"
        entries.append(_entry(number, link, slug, doc))
    if directory.is_dir():
        for doc in sorted(directory.glob("*.md")):
            if doc.name.lower() != EXPLAINER_FILE.lower():
                entries.append(_entry("", doc.name, doc.stem, doc))
    return entries


def is_generated_index(text: str) -> bool:
    """Tell whether ``docs/explain/README.md`` was written by KingmaDoc (safe to replace).

    Args:
        text: The file's content.

    Returns:
        True for an index from :func:`index_markdown`.
    """
    return INDEX_MARKER in text or text.startswith(INDEX_TITLE + "\n")


def index_markdown(entries: Sequence[Entry]) -> str:
    """Render ``docs/explain/README.md``: one row per explainer.

    Args:
        entries: From :func:`read_entries`.

    Returns:
        The Markdown index.
    """
    lines = [
        INDEX_TITLE,
        "",
        INDEX_MARKER,
        "",
        "One folder per explained subject (`<ID>-<name>/`), written by the KingmaDoc",
        "`explaining-code` skill. IDs are never reused. Regenerated by `kingmadoc explain`",
        "and `kingmadoc render`; do not edit by hand.",
        "",
        "| ID | Subject | Scope | Date |",
        "| --- | --- | --- | --- |",
    ]
    for e in entries:
        lines.append(f"| {e.id} | [{_cell(e.name)}]({e.link}) | {_cell(e.scope)} | {e.date} |")
    if not entries:
        lines.append("| | _No explainers yet._ | | |")
    return "\n".join(lines) + "\n"


def index_path(document: Path) -> Path | None:
    """Return the index a rendered document belongs to, or None outside explainer folders.

    Args:
        document: A document passed to ``kingmadoc render``.

    Returns:
        ``docs/explain/README.md`` when ``document`` is ``docs/explain/<NNNN>-<slug>/…``.
    """
    folder = document.resolve().parent
    parts = EXPLAIN_DIR.parts
    if _FOLDER.fullmatch(folder.name) and folder.parent.parts[-len(parts):] == parts:
        return folder.parent / EXPLAINER_FILE
    return None


@dataclass(frozen=True)
class Freshness:
    """Whether the code an explainer describes changed since the commit it is based on."""

    folder: Path
    commit: str | None
    changed: tuple[str, ...]
    whole_project: bool
    problem: str | None


def explainer_folders(directory: Path) -> list[Path]:
    """Return the ``<NNNN>-<slug>`` folders in ``directory``, in ID order.

    Args:
        directory: The ``docs/explain`` directory.

    Returns:
        The folder paths (empty when the directory does not exist).
    """
    return [folder for _, folder in _folders(directory)]


def based_on_commit(text: str) -> str | None:
    """Return the commit in an explainer's **Based on** row.

    Args:
        text: The explainer.

    Returns:
        The (abbreviated) commit hash, or None when the row or the hash is missing.
    """
    row = _BASED_ON_ROW.search(text)
    commit = _COMMIT.search(row.group(1)) if row else None
    return commit.group(0) if commit else None


def referenced_paths(text: str, root: Path) -> list[str]:
    """Return the project files and folders an explainer names in `code spans`.

    Args:
        text: The explainer.
        root: Project root; only paths that exist under it count.

    Returns:
        Sorted POSIX paths relative to ``root``; ``:line`` suffixes are dropped.
    """
    found = set()
    for span in _CODE_SPAN.findall(text):
        candidate = re.sub(r"(:\d+.*|#.*)$", "", span.strip()).rstrip("/")
        parts = candidate.split("/")
        if (
            candidate in ("", ".")
            or candidate.startswith("/")
            or any(c in candidate for c in " *?<>|\\:")
            or ".." in parts
        ):
            continue
        if (root / candidate).exists():
            found.add(candidate)
    return sorted(found)


def freshness(root: Path, folder: Path) -> Freshness:
    """Compare an explainer with the code: what changed since its **Based on** commit.

    Committed and uncommitted changes count; changes under ``docs/explain`` do not.
    Only the paths the explainer names are compared, or the whole project if it names
    none.

    Args:
        root: Project root (inside a git repository).
        folder: The explainer folder (``docs/explain/<NNNN>-<slug>``).

    Returns:
        The result; ``problem`` says why it could not be compared.
    """
    docs = sorted(folder.glob("*.md"), key=lambda p: p.name.lower() != EXPLAINER_FILE.lower())
    text = "\n".join(p.read_text(encoding="utf-8", errors="replace") for p in docs)
    commit = based_on_commit(text)
    paths = referenced_paths(text, root)

    def result(changed: tuple[str, ...] = (), problem: str | None = None) -> Freshness:
        return Freshness(folder, commit, changed, not paths, problem)

    if commit is None:
        return result(problem="no commit in its **Based on** row")
    if run_git(root, "rev-parse", "--verify", "--quiet", f"{commit}^{{commit}}") is None:
        return result(problem=f"commit {commit} is not in this repository")
    output = run_git(
        root, "diff", "--relative", "--name-only", commit, "--",
        *(paths or ["."]), f":(exclude){EXPLAIN_DIR.as_posix()}",
    )
    if output is None:
        return result(problem="git could not compare it")
    return result(changed=tuple(sorted(line for line in output.splitlines() if line)))


def _entry(number: str, link: str, fallback: str, doc: Path) -> Entry:
    text = doc.read_text(encoding="utf-8", errors="replace") if doc.is_file() else ""
    text = _FENCE.sub("", text)
    title, scope, date = _TITLE.search(text), _SCOPE.search(text), _BASED_ON.search(text)
    return Entry(
        id=number,
        link=link,
        name=title.group(1).strip() if title else fallback,
        scope=scope.group(1) if scope else "",
        date=date.group(1) if date else "",
    )


def _cell(text: str) -> str:
    """One line (CRLF files, U+2028), with what would end a cell or a link escaped."""
    text = " ".join(text.split())
    return re.sub(r"([\\|\[\]])", r"\\\1", text)


def _folders(directory: Path) -> list[tuple[int, Path]]:
    if not directory.is_dir():
        return []
    found = [(int(m.group(1)), p) for p in directory.iterdir()
             if p.is_dir() and (m := _FOLDER.fullmatch(p.name))]
    return sorted(found)


# A placeholder the scaffold or a reference format left, e.g. "<one line>"; HTML tags
# and the render comment are not placeholders.
_PLACEHOLDER = re.compile(
    r"<(?!!--|/?(?:details|summary|br|code|img|sub|sup|kbd|a)\b|https?:|mailto:)"
    r"(?![^<>\n]*@[^<>\n]*>)[^<>\n]{2,}>"
)
_IMAGE_LINK = re.compile(r"!\[[^\]]*\]\(([^)\s]+)\)")
EXPLAINER_DOCUMENTS = ("README.md", "functional.md", "technical.md")


def check_explainer(folder: Path) -> list[str]:
    """Everything that keeps an explainer from being finished; empty when it is.

    An explainer is finished when every document is filled in (no ``<placeholder>``
    left), every diagram is rendered (no D2 source), every image it links exists, and
    each document with figures shows at least one picture. The index and a split
    cover page need no picture.

    Args:
        folder: ``docs/explain/<NNNN>-<slug>``.

    Returns:
        One message per problem, with the file it is in.
    """
    documents = [folder / name for name in EXPLAINER_DOCUMENTS if (folder / name).is_file()]
    if not documents:
        return [f"{folder}: no explainer documents (README.md) yet"]
    problems = []
    for document in documents:
        text = document.read_text(encoding="utf-8", errors="replace")
        prose = _FENCE.sub("", text)
        name = document.name
        if not prose.strip():
            problems.append(f"{name}: empty")
            continue
        if "```d2" in text:
            problems.append(f"{name}: D2 source not rendered (run kingmadoc render)")
        # Code spans may hold generics like `List<Order>`; they are never placeholders.
        left = sorted(set(_PLACEHOLDER.findall(_CODE_SPAN.sub("", prose))))
        if left:
            shown = ", ".join(left[:3]) + (" …" if len(left) > 3 else "")
            problems.append(f"{name}: {len(left)} placeholders not filled in: {shown}")
        links = [t for t in _IMAGE_LINK.findall(text) if "://" not in t]
        # An embedded image (data URI) is always there.
        missing = [
            t for t in links if not t.startswith("data:") and not (document.parent / t).is_file()
        ]
        if missing:
            problems.append(f"{name}: missing images: {', '.join(missing)}")
        figures = "**Figure " in text
        if figures and not links:
            problems.append(f"{name}: has figure captions but shows no pictures")
    return problems


def count_pictures(folder: Path) -> int:
    """The number of pictures an explainer shows: embedded and linked images together.

    Args:
        folder: ``docs/explain/<NNNN>-<slug>``.

    Returns:
        Image links (data URIs included) over all its documents.
    """
    return sum(
        len(_IMAGE_LINK.findall((folder / name).read_text(encoding="utf-8", errors="replace")))
        for name in EXPLAINER_DOCUMENTS
        if (folder / name).is_file()
    )


_SOURCE_COMMENT = re.compile(r"^<!-- kingmadoc:diagram (img/[\w.-]+\.d2) -->$", re.M)
_CAPTION = re.compile(r"^\*\*Figure \d+\.\*\*.*$", re.M)
# A D2 label: the quoted or plain text after `key:` (up to `{`, `;` or the line end).
_D2_LABEL = re.compile(r'^\s*[\w.-]+\s*:\s*(?:"((?:[^"\\\n]|\\.)*)"|([^{;\n"]+))', re.M)
# Wireframe marks that are drawing, not text of the view.
_WIREFRAME_MARK = re.compile(r"\[ *_* *\]|☐|☑| v$|^[+|!*]\s*|\s*\*$")


def screen_warnings(folder: Path, root: Path) -> list[str]:
    """Texts in ``[Screen]`` wireframes that the view they show does not contain.

    Best effort: a figure whose D2 title has ``[Screen]`` and whose caption names a
    view file in a code span (e.g. `` `src/views/contact.html` ``) is checked label by
    label against that file's text. Wireframes must use the view's own words.

    Args:
        folder: ``docs/explain/<NNNN>-<slug>``.
        root: The project root the view paths are relative to.

    Returns:
        One message per label not found in the view.
    """
    warnings = []
    for name in EXPLAINER_DOCUMENTS:
        document = folder / name
        if not document.is_file():
            continue
        text = document.read_text(encoding="utf-8", errors="replace")
        for comment in _SOURCE_COMMENT.finditer(text):
            source_file = folder / comment.group(1)
            if not source_file.is_file():
                continue
            source = source_file.read_text(encoding="utf-8", errors="replace")
            if "[Screen]" not in source:
                continue
            caption = _CAPTION.search(text, comment.end())
            views = [
                root / span
                for span in (_CODE_SPAN.findall(caption.group(0)) if caption else [])
                if (root / span).is_file()
            ]
            if not views:
                continue
            view_text = " ".join(v.read_text(encoding="utf-8", errors="replace") for v in views)
            for match in _D2_LABEL.finditer(source):
                label = (match.group(1) or match.group(2) or "").strip()
                label = _WIREFRAME_MARK.sub("", label).strip().strip(":").strip()
                if len(label) < 2 or "[Screen]" in label or label.startswith(("/", "#")):
                    continue
                if label not in view_text:
                    warnings.append(f"{name}: {comment.group(1)}: `{label}` is not in "
                                    f"{', '.join(v.relative_to(root).as_posix() for v in views)}")
    return warnings


# C4 actors: people and external systems, as the C4 classes in c4-model.md draw them.
_C4_KIND = re.compile(r'^title: "\[(System Context|Container|Component|Deployment)\]', re.M)
_MD_ELEMENT = re.compile(
    r"^[ \t]*([\w-]+):[ \t]*\|md\n(.*?)\n[ \t]*\|[ \t]*\{([^}\n]*)\}", re.M | re.S
)
_LINE_ELEMENT = re.compile(
    r'^[ \t]*([\w-]+):[ \t]*("[^"\n]*"|[^{\n|"]*?)[ \t]*\{([^}\n]*)\}[ \t]*$', re.M
)
_EDGE = re.compile(r"^\s*([\w.-]+)\s*(?:<->|->|<-|--)\s*([\w.-]+)", re.M)


_D2_LEGEND = re.compile(r"vars:\s*\{\s*d2-legend:\s*\{.*?^\s*\}\s*^\}", re.S | re.M)


def _actors(source: str) -> list[tuple[str, str, str]]:
    """``(key, name, "person"/"external")`` of a D2 figure's actors, in declaration order."""
    source = _D2_LEGEND.sub("", source)
    found = []
    for pattern, markdown in ((_MD_ELEMENT, True), (_LINE_ELEMENT, False)):
        for match in pattern.finditer(source):
            key, label, attrs = match.groups()
            if "c4-person" in attrs or re.search(r"\bclass: *person\b", attrs):
                kind = "person"
            elif re.search(r"\bclass: *external\b", attrs):
                kind = "external"
            else:
                continue
            if markdown:
                bold = re.search(r"\*\*(.+?)\*\*", label)
                name = bold.group(1) if bold else label.strip()
            else:
                name = re.sub(r"\s*\[[^\]]*\]\s*$", "", label.strip().strip('"')).strip()
            found.append((match.start(), key, name or key, kind))
    return [(key, name, kind) for _, key, name, kind in sorted(found)]


def c4_actor_warnings(figures: Sequence[tuple[str, str]]) -> list[str]:
    """The context's people and external systems, compared with every lower C4 figure.

    Per ``[Container]``, ``[Component]`` and ``[Deployment]`` figure: (a) an actor of the
    ``[System Context]`` figure that the figure has an arrow to but does not declare,
    (b) a person or external system the context does not have (new, or renamed), and
    (c) external systems declared in another order than in the context (ELK places them
    at the bottom in that order).

    Args:
        figures: ``(name, D2 source)`` per figure, e.g. ``("img/figure-2.d2", "...")``.

    Returns:
        One message per problem (empty without a context figure).
    """
    kinds = [(name, source, _C4_KIND.search(source)) for name, source in figures]
    context = next((s for _, s, k in kinds if k and k.group(1) == "System Context"), None)
    if context is None:
        return []
    expected = _actors(context)
    by_name = {name: (key, kind) for key, name, kind in expected}
    warnings = []
    for name, source, kind in kinds:
        if not kind or kind.group(1) == "System Context":
            continue
        actors = _actors(source)
        names = {actor_name for _, actor_name, _ in actors}
        keys = {key for key, _, _ in actors}
        ends = {part for edge in _EDGE.findall(source) for end in edge for part in end.split(".")}
        for key, actor_name, _ in expected:
            if actor_name not in names and key not in keys and key in ends:
                warnings.append(f"{name}: `{actor_name}` from the context is missing; declare it "
                                "with the same key, name and class")
        context_names = {key: actor_name for key, actor_name, _ in expected}
        for key, actor_name, actor_kind in actors:
            if actor_name in by_name:
                continue
            if key in context_names:
                warnings.append(f"{name}: {actor_kind} `{actor_name}` is called "
                                f"`{context_names[key]}` in the context; use the same name")
            else:
                warnings.append(f"{name}: {actor_kind} `{actor_name}` is not in the context; "
                                "add it there, or move the role to the stakeholders table")
        order = [n for _, n, k in expected if k == "external"]
        here = [n for _, n, k in actors if k == "external" and n in by_name]
        if here != [n for n in order if n in here]:
            warnings.append(f"{name}: external systems in another order than in the context "
                            f"({', '.join(here)}); declare them as {', '.join(order)}")
    return warnings


def explainer_figures(folder: Path) -> list[tuple[str, str]]:
    """``(img/<name>.d2, source)`` of every rendered figure of an explainer, in order.

    Args:
        folder: ``docs/explain/<NNNN>-<slug>``.

    Returns:
        The D2 sources the documents point to (missing files skipped).
    """
    figures = []
    for name in EXPLAINER_DOCUMENTS:
        document = folder / name
        if not document.is_file():
            continue
        text = document.read_text(encoding="utf-8", errors="replace")
        for comment in _SOURCE_COMMENT.finditer(text):
            source = folder / comment.group(1)
            if source.is_file():
                figures.append((comment.group(1), source.read_text(encoding="utf-8")))
    return figures


_PARTICIPANT = re.compile(r'^([\w-]+):[ \t]*"?([^{\n"]*)"?', re.M)
_NOT_PARTICIPANTS = frozenset({"title", "shape", "classes", "vars", "style", "direction"})


def lifeline_warnings(figures: Sequence[tuple[str, str]]) -> list[str]:
    """Sequence-diagram lifelines that merge two code elements (``A / B``).

    One lifeline is one class, file or external system; the only exception is a page with
    its own script of the same base name (``index.html / index.js``).

    Args:
        figures: ``(name, D2 source)`` per figure, e.g. ``("img/figure-2.d2", "...")``.

    Returns:
        One message per merged lifeline.
    """
    warnings = []
    for name, source in figures:
        if not re.search(r"\bshape: *sequence_diagram\b", source):
            continue
        for key, label in _PARTICIPANT.findall(source):
            label = label.strip()
            if key in _NOT_PARTICIPANTS or " / " not in label:
                continue
            parts = [p.strip() for p in label.split(" / ")]
            stems = {Path(p).stem.lower() for p in parts}
            suffixes = sorted(Path(p).suffix.lower() for p in parts)
            if len(parts) == 2 and len(stems) == 1 and suffixes in (
                [".htm", ".js"], [".html", ".js"], [".html", ".ts"], [".htm", ".ts"]
            ):
                continue  # a page and its own script
            warnings.append(f"{Path(name).name}: lifeline '{label}' merges two classes; "
                            "give each its own lifeline")
    return warnings
