"""Explainer folders: one per explained subject, ``docs/explain/<NNNN>-<slug>/``.

Each subject (a feature, branch, project or part) gets a unique, never reused ID and a
name. Its folder holds the explainer (``README.md``) and its pictures (``img/``);
``docs/explain/README.md`` lists them all. Explaining the same subject again reuses its
folder, so the ID and links stay stable.
"""

from __future__ import annotations

import re
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

from kingmadoc.exceptions import ExplainError
from kingmadoc.git import run_git
from kingmadoc.naming import slugify

EXPLAIN_DIR = Path("docs/explain")
EXPLAINER_FILE = "README.md"
ID_WIDTH = 4
_FOLDER = re.compile(r"(\d{4,})-(.+)")
_TITLE = re.compile(r"^#\s+(.+?)(?::\s.*)?$", re.M)
_SCOPE = re.compile(r"^\|\s*\*\*Scope\*\*\s*\|\s*(.*?)\s*\|", re.M)
_BASED_ON = re.compile(r"^\|\s*\*\*Based on\*\*\s*\|.*?(\d{4}-\d{2}-\d{2})", re.M)
_FENCE = re.compile(r"^(```|~~~).*?^\1[ \t]*$", re.S | re.M)
INDEX_TITLE = "# Explained code"
_BASED_ON_ROW = re.compile(r"^\|\s*\*\*Based on\*\*\s*\|(.*)$", re.M)
_COMMIT = re.compile(r"\b[0-9a-f]{7,40}\b")
_CODE_SPAN = re.compile(r"`([^`\n]+)`")
INDEX_MARKER = "<!-- kingmadoc:explain-index -->"


@dataclass(frozen=True)
class Entry:
    """One explainer folder, as listed in the index."""

    id: str
    link: str
    name: str
    scope: str
    date: str


def explainer_folder(root: Path, name: str) -> tuple[Path, bool]:
    """Return the folder for a subject, creating it with a new ID when it is new.

    Args:
        root: Project root.
        name: Subject name ("Contact form", "branch feature-x") or an existing ID ("3").

    Returns:
        ``(folder, created)``.

    Raises:
        ExplainError: If the name is blank or the folder cannot be created.
    """
    slug = slugify(name) if name.strip() else ""
    if not slug:
        raise ExplainError("The subject needs a name, e.g. kingmadoc explain new \"Contact form\"")
    directory = root / EXPLAIN_DIR
    folders = _folders(directory)
    wanted_id = int(name) if name.strip().isdigit() else None
    for number, folder in folders:
        if folder.name.partition("-")[2] == slug or number == wanted_id:
            return folder, False
    number = max((n for n, _ in folders), default=0) + 1
    folder = directory / f"{number:0{ID_WIDTH}d}-{slug}"
    try:
        folder.mkdir(parents=True)
    except OSError as exc:
        raise ExplainError(f"Cannot create {folder}: {exc}") from exc
    return folder, True


def read_entries(directory: Path) -> list[Entry]:
    """Read the name, scope and date of every explainer folder in ``directory``.

    Args:
        directory: The ``docs/explain`` directory.

    Returns:
        The entries in ID order; the folder's slug stands in for a missing explainer.
        Explainers from before the folders (``docs/explain/<slug>.md``) follow, without ID.
    """
    entries = []
    for _, folder in _folders(directory):
        number, _, slug = folder.name.partition("-")
        doc = folder / EXPLAINER_FILE
        link = f"{folder.name}/{EXPLAINER_FILE}" if doc.is_file() else f"{folder.name}/"
        entries.append(_entry(number, link, slug, doc))
    if directory.is_dir():
        for doc in sorted(directory.glob("*.md")):
            if doc.name.lower() != EXPLAINER_FILE.lower():
                entries.append(_entry("", doc.name, doc.stem, doc))
    return entries


def is_generated_index(text: str) -> bool:
    """Tell whether ``docs/explain/README.md`` was written by KingmaDoc (safe to replace).

    Args:
        text: The file's content.

    Returns:
        True for an index from :func:`index_markdown`.
    """
    return INDEX_MARKER in text or text.startswith(INDEX_TITLE + "\n")


def index_markdown(entries: Sequence[Entry]) -> str:
    """Render ``docs/explain/README.md``: one row per explainer.

    Args:
        entries: From :func:`read_entries`.

    Returns:
        The Markdown index.
    """
    lines = [
        INDEX_TITLE,
        "",
        INDEX_MARKER,
        "",
        "One folder per explained subject (`<ID>-<name>/`), written by the KingmaDoc",
        "`explaining-code` skill. IDs are never reused. Regenerated by `kingmadoc explain`",
        "and `kingmadoc render`; do not edit by hand.",
        "",
        "| ID | Subject | Scope | Date |",
        "| --- | --- | --- | --- |",
    ]
    for e in entries:
        lines.append(f"| {e.id} | [{_cell(e.name)}]({e.link}) | {_cell(e.scope)} | {e.date} |")
    if not entries:
        lines.append("| | _No explainers yet._ | | |")
    return "\n".join(lines) + "\n"


def index_path(document: Path) -> Path | None:
    """Return the index a rendered document belongs to, or None outside explainer folders.

    Args:
        document: A document passed to ``kingmadoc render``.

    Returns:
        ``docs/explain/README.md`` when ``document`` is ``docs/explain/<NNNN>-<slug>/…``.
    """
    folder = document.resolve().parent
    parts = EXPLAIN_DIR.parts
    if _FOLDER.fullmatch(folder.name) and folder.parent.parts[-len(parts):] == parts:
        return folder.parent / EXPLAINER_FILE
    return None


@dataclass(frozen=True)
class Freshness:
    """Whether the code an explainer describes changed since the commit it is based on."""

    folder: Path
    commit: str | None
    changed: tuple[str, ...]
    whole_project: bool
    problem: str | None


def explainer_folders(directory: Path) -> list[Path]:
    """Return the ``<NNNN>-<slug>`` folders in ``directory``, in ID order.

    Args:
        directory: The ``docs/explain`` directory.

    Returns:
        The folder paths (empty when the directory does not exist).
    """
    return [folder for _, folder in _folders(directory)]


def based_on_commit(text: str) -> str | None:
    """Return the commit in an explainer's **Based on** row.

    Args:
        text: The explainer.

    Returns:
        The (abbreviated) commit hash, or None when the row or the hash is missing.
    """
    row = _BASED_ON_ROW.search(text)
    commit = _COMMIT.search(row.group(1)) if row else None
    return commit.group(0) if commit else None


def referenced_paths(text: str, root: Path) -> list[str]:
    """Return the project files and folders an explainer names in `code spans`.

    Args:
        text: The explainer.
        root: Project root; only paths that exist under it count.

    Returns:
        Sorted POSIX paths relative to ``root``; ``:line`` suffixes are dropped.
    """
    found = set()
    for span in _CODE_SPAN.findall(text):
        candidate = re.sub(r"(:\d+.*|#.*)$", "", span.strip()).rstrip("/")
        parts = candidate.split("/")
        if (
            candidate in ("", ".")
            or candidate.startswith("/")
            or any(c in candidate for c in " *?<>|\\:")
            or ".." in parts
        ):
            continue
        if (root / candidate).exists():
            found.add(candidate)
    return sorted(found)


def freshness(root: Path, folder: Path) -> Freshness:
    """Compare an explainer with the code: what changed since its **Based on** commit.

    Committed and uncommitted changes count; changes under ``docs/explain`` do not.
    Only the paths the explainer names are compared, or the whole project if it names
    none.

    Args:
        root: Project root (inside a git repository).
        folder: The explainer folder (``docs/explain/<NNNN>-<slug>``).

    Returns:
        The result; ``problem`` says why it could not be compared.
    """
    docs = sorted(folder.glob("*.md"), key=lambda p: p.name.lower() != EXPLAINER_FILE.lower())
    text = "\n".join(p.read_text(encoding="utf-8", errors="replace") for p in docs)
    commit = based_on_commit(text)
    paths = referenced_paths(text, root)

    def result(changed: tuple[str, ...] = (), problem: str | None = None) -> Freshness:
        return Freshness(folder, commit, changed, not paths, problem)

    if commit is None:
        return result(problem="no commit in its **Based on** row")
    if run_git(root, "rev-parse", "--verify", "--quiet", f"{commit}^{{commit}}") is None:
        return result(problem=f"commit {commit} is not in this repository")
    output = run_git(
        root, "diff", "--relative", "--name-only", commit, "--",
        *(paths or ["."]), f":(exclude){EXPLAIN_DIR.as_posix()}",
    )
    if output is None:
        return result(problem="git could not compare it")
    return result(changed=tuple(sorted(line for line in output.splitlines() if line)))


def _entry(number: str, link: str, fallback: str, doc: Path) -> Entry:
    text = doc.read_text(encoding="utf-8", errors="replace") if doc.is_file() else ""
    text = _FENCE.sub("", text)
    title, scope, date = _TITLE.search(text), _SCOPE.search(text), _BASED_ON.search(text)
    return Entry(
        id=number,
        link=link,
        name=title.group(1).strip() if title else fallback,
        scope=scope.group(1) if scope else "",
        date=date.group(1) if date else "",
    )


def _cell(text: str) -> str:
    """One line (CRLF files, U+2028), with what would end a cell or a link escaped."""
    text = " ".join(text.split())
    return re.sub(r"([\\|\[\]])", r"\\\1", text)


def _folders(directory: Path) -> list[tuple[int, Path]]:
    if not directory.is_dir():
        return []
    found = [(int(m.group(1)), p) for p in directory.iterdir()
             if p.is_dir() and (m := _FOLDER.fullmatch(p.name))]
    return sorted(found)
